version: "3.4"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=toluwase
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_DATABASE=metaverse_db
    ports:
      - $MYSQLDB_LOCAL_PORT:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - auth-networks

  server:
    build: ./server
    depends_on:
      - mysqldb
    env_file: ./.env
    restart: unless-stopped
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=toluwase
      - DB_NAME=metaverse_db
    ports:
      - $NODE_LOCAL_PORT:4000
    networks:
      - auth-networks
    command: npm start

networks:
  auth-networks:
    driver: bridge

volumes:
  db:
