version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - PORT=4000
      - JWT_SECRET=your_jwt_secret
      - DATABASE_URL=mysql://user:password@db:3306/metaverse_magna
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toluwase
      MYSQL_DATABASE: metaverse_magna
      MYSQL_USER: root
      MYSQL_PASSWORD: toluwase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
