version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/metaverse_db
      - JWT_SECRET=your_jwt_secret
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: metaverse_db
      MYSQL_USER: root
      MYSQL_PASSWORD: toluwase
      MYSQL_ROOT_PASSWORD: toluwase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
